### ISSUE TITLE
Missing flags

### ISSUE THREAD

**Issue by petervel** [VincentSmit/cappening#17]
In our Happening (#2) half the flags have disappeared. Only the green flags are still visible.

**Comment by ProCessor00** [comment]
Thanks for notifying. We are aware of the issue, we are working on a fix (probably deployed tonight)

**Comment by NLthijs48** [comment]
This problem has been fixed.

I had removed some version upgrade code in order to cleanup before release, but since not everyone had deployed this version upgrade code, old games got messed up when deploying the latest version (old games had wrong color data, and because of that tried to load the beacon icons by an incorrect name, causing it to error and not render the beacon).
